# Laboratorio 5: Clasificación 🤗

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>


### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: María Jesús Valenzuela
- Nombre de alumno 2: Matías Zúñiga

### **Link de repositorio de GitHub:** [Insertar Repositorio](https://github.com/jesuvalenzuela/NanSquad)

### Temas a tratar
- Clasificación en problemas desbalanceados
- Lightgbm y xgboost
- Pipelines

## Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.





### Objetivos principales del laboratorio
- Comprender cómo trabajar con problemas de clasificación con clases desbalanceadas.
- Aplicar los modelos lightgbm y xgboost.
- Practicar Pipelines

# Parte Teórica [12 puntos]




1. Explique cuál es la diferencia entre los datos de entrenamiento y validación. [1 punto]

2. Explique cuál es el principal desafío al trabajar problemas de clasificación con data no supervisada. [1 punto]

3. Explique en **sus palabras** qué es la matriz de confusión y para qué se utiliza. [1 puntos]

4. Escriba la fórmula de las siguientes métricas y explique con **sus palabras** cómo se interpretan. [1 punto cada uno]

  * Accuracy
  * Precision
  * Recall
  * F1 score

5. Explique qué métrica recomendaría para los siguientes contextos de clasificación. [1 punto cada uno]

  * Mantenimiento predictivo de fallas de maquinaria pesada en la industria minera.  
  * Detección de enfermedades altamente contagiosas.
  * Aprobación de créditos de alto riesgo.
  * Detección de crímenes.

6. Explique qué es la calibración de modelos y para qué se usa. [1 punto]


**Respuesta:**

1. Los datos de entrenamiento se usan para "ajustar" el modelo, mientras que los datos de validación se utilizar para evaluar la calidad de este ajuste.

2. Los modelos de clasificación requieren, por definición, etiquetas (datos supervisados) para su entrenamiento y validación. Por lo tanto, el principal desafío sería etiquetar los datos para posibilitar el desarrollo de modelos de clasificación.

3. La matriz de confusión entrega un resumen del desempeño de un modelo de clasificación. Un eje representa las clases reales y el otro las clases predichas. Por ejemplo, si el eje X representa la clase real y el eje Y la predicha, cada "celda" (x, y) indica cuantos puntos que pertenecen realmente a la clase x fueron clasificados por el modelo en la clase y.
Esta permite visualizar, para cada clase, cuantos valores fueron clasificados correctamente y cuantos no.

4. 
$$Accuracy = (TP + TN) / (TP + TN + FP + FN)$$
Representa la cantidad de puntos correctamente clasificados, sobre el total de predicciones.

$$Precision = TP / (TP + FP)$$
De todas las predicciones positivas que hizo el modelo, cuántas fueron correctas.

$$Recall = TP / (TP + FN)$$
De todos los casos positivos, cuantos fueron predichos correctamente.

$$F1-score = 2 × (Precision × Recall) / (Precision + Recall)$$
Es un equilibrio entre precision (que castiga falsos positivos) y recall (que castiga falsos negativos).


5. 
  * Mantenimiento predictivo de fallas de maquinaria pesada en la industria minera: Recall - Es importante detectar todas las fallas. Es preferible tener algunos falsos positivos (mantenimiento innecesario) que omitir una falla real.
  * Detección de enfermedades altamente contagiosas: Recall - No detectar un caso positivo generaría que el paciente no tome precauciones. Es preferible tener algunos falsos positivos (cuarentenas innecesarias) que omitir casos reales.
  * Aprobación de créditos de alto riesgo: Precision - Es mejor minimizar los falsos positivos (aprobar malos créditos), ya que es preferible rechazar algunos buenos clientes que aprobar malos pagadores.
  * Detección de crímenes: F1-score - No es deseable dejar criminales libres ni encarcelar personas inocentes, por lo que se recomienta esta métrica que balancea ambos escenarios.

6. La calibración de modelos se refiere a ajustar las probabilidades predichas por un modelo a las frecuencias observadas en la realidad. Un modelo bien calibrado puede utilizarse para gestión de riesgo o toma de decisiones, considerando las predicciones del modelo para identificar los escenarios más probables.


# Parte práctica [48 puntos]

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones.

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con el csv `statsplayers.csv`, donde deberán aplicar algoritmos de aprendizaje supervisado de clasificación en base a características que describen de jugadores de fútbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [ ]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = 'Dirección donde tiene los archivos en el Drive'
except:
    print('Ignorando conexión drive-colab')

In [76]:
# Librerías 
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.model_selection import train_test_split

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

from sklearn.linear_model import SGDClassifier

In [63]:
df = pd.read_csv('stats_players.csv')
df

Name          Nationality National_Position Club_Position  \
0      Cristiano Ronaldo             Portugal                LS            LW   
1           Lionel Messi            Argentina                RW            RW   
2                 Neymar               Brazil                LW            LW   
3            Luis Suárez              Uruguay                LS            ST   
4           Manuel Neuer              Germany                GK            GK   
...                  ...                  ...               ...           ...   
17583        Adam Dunbar  Republic of Ireland               NaN           Sub   
17584       Dylan McGoey  Republic of Ireland               NaN           Sub   
17585    Tommy Ouldridge              England               NaN           Res   
17586         Mark Foden             Scotland               NaN           Sub   
17587   Barry Richardson              England               NaN           Sub   

       Height  Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  \
0         185      80          Right   32       High / Low          4  ...   
1         170      72           Left   29  Medium / Medium          4  ...   
2         174      68          Right   25    High / Medium          5  ...   
3         182      85          Right   30    High / Medium          4  ...   
4         193      92          Right   31  Medium / Medium          4  ...   
...       ...     ...            ...  ...              ...        ...  ...   
17583     183      82          Right   19  Medium / Medium          1  ...   
17584     185      80          Right   19  Medium / Medium          2  ...   
17585     173      61          Right   18    High / Medium          2  ...   
17586     180      80          Right   21  Medium / Medium          3  ...   
17587     185      77          Right   47  Medium / Medium          2  ...   

       Agility  Jumping  Heading  Shot_Power  Finishing  Long_Shots  Curve  \
0           90       95       85          92         93          90     81   
1           90       68       71          85         95          88     89   
2           96       61       62          78         89          77     79   
3           86       69       77          87         94          86     86   
4           52       78       25          25         13          16     14   
...        ...      ...      ...         ...        ...         ...    ...   
17583       27       56       14          16         13          13     11   
17584       28       53       12          17         12          11     12   
17585       54       61       41          44         28          42     35   
17586       34       48       15          23         14          12     13   
17587       38       51       12          13         11          16     12   

       Freekick_Accuracy  Penalties  Volleys  
0                     76         85       88  
1                     90         74       85  
2                     84         81       83  
3                     84         85       88  
4                     11         47       11  
...                  ...        ...      ...  
17583                 13         15       12  
17584                 13         16       12  
17585                 36         42       37  
17586                 12         24       12  
17587                 11         22       12  

[17588 rows x 39 columns]

## 1. Predicción de Seleccionados Nacionales [14 puntos]

<p align="center">
  <img src="https://www.futuro.cl/wp-content/uploads/2016/06/chile-argentina-meme-12.jpg" width="300">
</p>



### 1.1 Preprocesamiento [5 puntos]

Tareas:

1. Genere los labels para la clasificación binaria en una variable llamada `label`. Para esto, trabaje sobre el atributo `National_Position` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. [Sin puntaje]

2. Hecho esto, ¿cuántos se tienen ejemplos por cada clase? Comente lo que observa. [1 punto]

3. Genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guárdelo una variable llamada `col_transformer`. [2 puntos]

4. Comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material `Player_Stats_Report.html` que viene en el zip del lab), al igual que las transformaciones aplicadas. [2 puntos]

**Respuesta:**

#### 1. Generación de labels

In [64]:
def jugador_seleccionado(pos):
    """Retorna 1 si un jugador fue seleccionado (tiene una posición válida) y 
    0 si un jugador no fue seleccionado (su posición es Nan)."""
    if pd.isna(pos):
        return 0
    else:
        return 1

# Crear labels
y = df['National_Position'].apply(jugador_seleccionado)

# Definir X (datos)
X = df.drop(columns=['National_Position']).copy()


#### 2. Ejemplos por clase

In [32]:
# Contar ejemplos por clase
y.value_counts()

label
0    16513
1     1075
Name: count, dtype: int64

In [ ]:
X.columns

Index(['Name', 'Nationality', 'Club_Position', 'Height', 'Weight',
       'Preffered_Foot', 'Age', 'Work_Rate', 'Weak_foot', 'Skill_Moves',
       'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
       'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision',
       'Composure', 'Crossing', 'Short_Pass', 'Long_Pass', 'Acceleration',
       'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping',
       'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve',
       'Freekick_Accuracy', 'Penalties', 'Volleys'],
      dtype='object')

Hay un evidente desbalance de clases, donde la mayoría de los jugadores pertenece a la clase 0 (no seleccionado).

#### 3. Column Transformer

In [55]:
# Columnas a eliminar (alta correlación, cardinalidad)
columns_to_drop = [
    'Name', 'Nationality', # Alta cardinalidad
    'Standing_Tackle', 'Ball_Control', 'Short_Pass', 'Weight', 'Reactions'  # Alta correlación
]

class ColumnDropper(BaseEstimator, TransformerMixin):
    def __init__(self, columns_to_drop):
        self.columns_to_drop = columns_to_drop
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        # Eliminar las columnas especificadas
        return X.drop(columns=self.columns_to_drop)
    
# Pipelines de transformación
numerical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(drop='first', sparse_output=False))
])

# Características numéricas
numerical_features = X.select_dtypes('number').columns.tolist()
numerical_features = [x for x in numerical_features if x not in columns_to_drop]

# Características categóricas
categorical_features = X.select_dtypes('object').columns.tolist()
categorical_features = [x for x in categorical_features if x not in columns_to_drop]

# ColumnTransformer
col_transformer = ColumnTransformer([
    ('num', numerical_pipeline, numerical_features),
    ('cat', categorical_pipeline, categorical_features),
    ('drop_cols', ColumnDropper(columns_to_drop), columns_to_drop)
], 
remainder='passthrough',
verbose_feature_names_out=False)


#### 4. Justificación ColumnTransformer

Se identificó las siguientes situaciones en el reporte:
1. **Alta Correlación:** Hay muchas variables que están fuertemente correlacionadas entre sí. Por ejemplo:
   * `Sliding_Tackle` y `Standing_Tackle`.
   * `Dribbling` y `Ball_Control`.
   * `Short_Pass` y `Ball_Control`.
   * `Height` y `Weight`.
   * `Overall` (valoración general) y `Reactions`.
   
Para evitar la multicolinealidad, se eliminó una de las variables de cada par altamente correlacionado.

2. **Alta Cardinalidad:** Las columnas `Name` y `Nationality` tienen demasiados valores únicos.
Estas columnas fueron eliminadas, ya que no aportan información generalizable.

El resto de transformaciones corresponde a procedimientos estándar, como imputar y escalar en variables numericas, e imputar y codificar en categoricas.

### 1.2 Entrenamiento [3 puntos]

Ahora, vamos a entrenar los pipelines generados en los pasos anteriores. Para esto, debe realizar las siguientes tareas:

1. Separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio). En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`). [1 puntos]

2. Defina un pipeline llamado `pipeline_xgboost` y otro llamado `pipeline_lightgbm`. Estos pipelines deben tener el mismo ColumnTransformer definido en la sección de preprocesamiento, pero deben variar los clasificadores de acuerdo al nombre de cada pipeline. [1 puntos]

3. Entrene los pipelines. [1 punto]


**Respuesta:**

#### 1. Split

Se usará 0.2 como test, valor estándar en aprendizaje de máquinas. La configuracion stratify=y asegura que se preserve la distribucion de clases.

In [56]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

#### 2. Pipelines

In [57]:
# Pipeline con XGBoost
pipeline_xgboost = Pipeline([
    ('preprocessor', col_transformer),
    ('classifier', XGBClassifier(
        random_state=42))
])

# Pipeline con LightGBM
pipeline_lightgbm = Pipeline([
    ('preprocessor', col_transformer),
    ('classifier', LGBMClassifier(
        random_state=42))
])

#### 3. Entrenamiento

In [58]:
# Entrenamiento
pipeline_xgboost.fit(X_train, y_train)
pipeline_lightgbm.fit(X_train, y_train)


[LightGBM] [Info] Number of positive: 860, number of negative: 13210
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000438 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2163
[LightGBM] [Info] Number of data points in the train set: 14070, number of used features: 62
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.061123 -> initscore=-2.731797
[LightGBM] [Info] Start training from score -2.731797


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Height', 'Age', 'Weak_foot',
                                                   'Skill_Moves', 'Dribbling',
                                                   'Marking', 'Sliding_Tackle',
                                                   'Aggression',
                                                   'Interceptions', 'Vision',
                                                   'Composure', 'Crossing',
                                                   'Long_Pass', 'Accelerat...
                                                  ['Club_Position',
                                                   'Preffered_Foot',
                                                   'Work_Rate']),
                                                 ('drop_cols',
                                                  ColumnDropper(columns_to_drop=['Name',
                                                                                 'Nationality',
                                                                                 'Standing_Tackle',
                                                                                 'Ball_Control',
                                                                                 'Short_Pass',
                                                                                 'Weight',
                                                                                 'Reactions']),
                                                  ['Name', 'Nationality',
                                                   'Standing_Tackle',
                                                   'Ball_Control', 'Short_Pass',
                                                   'Weight', 'Reactions'])],
                                   verbose_feature_names_out=False)),
                ('classifier', LGBMClassifier(random_state=42))])

### 1.3 Resultados [6 puntos]

1. Calcule las métricas accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) para evaluar el rendimiento de los distintos modelos. Verifique sus resultados usando `classification_report`. [2 puntos]

2. Explique qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) y cómo influye la cantidad de ejemplos por clase en los resultados obtenidos. [2 puntos]

3. Explique qué métrica le parece más adecuada y concluya qué modelo tiene un mejor desempeño. [2 puntos]

**Respuesta:**

#### 1. Metricas y classification report

In [61]:
# Métricas para xgboost
y_pred_xgb = pipeline_xgboost.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_xgb)
precision = precision_score(y_test, y_pred_xgb, pos_label=1)        # Clase positiva = 1
recall = recall_score(y_test, y_pred_xgb, pos_label=1)

print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")  
print(f"Recall:    {recall:.4f}")

print(classification_report(y_test, y_pred_xgb, 
                          target_names=['No Seleccionado', 'Seleccionado']))

Accuracy:  0.9352
Precision: 0.4133
Recall:    0.1442
                 precision    recall  f1-score   support

No Seleccionado       0.95      0.99      0.97      3303
   Seleccionado       0.41      0.14      0.21       215

       accuracy                           0.94      3518
      macro avg       0.68      0.57      0.59      3518
   weighted avg       0.91      0.94      0.92      3518



In [62]:
# Métricas para lightgbm
y_pred_lgb = pipeline_lightgbm.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_lgb)
precision = precision_score(y_test, y_pred_lgb, pos_label=1)        # Clase positiva = 1
recall = recall_score(y_test, y_pred_lgb, pos_label=1)

print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")  
print(f"Recall:    {recall:.4f}")

print(classification_report(y_test, y_pred_lgb, 
                          target_names=['No Seleccionado', 'Seleccionado']))

Accuracy:  0.9406
Precision: 0.5577
Recall:    0.1349
                 precision    recall  f1-score   support

No Seleccionado       0.95      0.99      0.97      3303
   Seleccionado       0.56      0.13      0.22       215

       accuracy                           0.94      3518
      macro avg       0.75      0.56      0.59      3518
   weighted avg       0.92      0.94      0.92      3518



/Users/jesu/Desktop/WORK/lab-programacion-cientifica/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


#### 2. Explicación de métricas
En ambos modelos, accuracy es mayor que precision y considerablemente mayor que recall. Esto se explica con el desbalance de clases que identificamos anteriormente, lo que generó que el modelo aprendiera mucho mejor cómo predecir la clase mayoriaria (no seleccionado). Entonces:

Precision global (41.33%): Cuando el modelo predice "Seleccionado", solo el 41% de estas son correctas
Recall global (14.42%): El modelo solo detecta el 14% de los casos que realmente son "Seleccionado"


#### 3. Métrica más apropiada

Dado que se quiere predecir a los jugadores seleccionados, recall (de todos los casos positivos, cuantos fueron predichos correctamente) es la mas apropiada. Considerando esta métrica, ambos modelos tienen muy mal desempeño, pero xgboost es ligeramente mejor.

## 2. Predicción de posiciones de jugadores [4 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="300">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas.

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características.

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo `Club_Position`, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF']
central_ataque = ['RW', 'CAM', 'LW']
central = ['RM', 'CM', 'LM']
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

La elección del clasificador se justificar en base a la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y se deben comentar los resultados obtenidos en la clasificación.

**Tareas:** [1 punto por tarea]

1. En un nuevo dataframe, aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección y guárdelos en la variable `label`.
2. Cuente cuántos por clase quedan.
3. Entrene el nuevo pipeline y ejecute una evaluación de este.  
4. Comente los resultados obtenidos.

**Respuesta:**

#### 1. etiquetas

In [65]:
df['Club_Position'].unique()

array(['LW', 'RW', 'ST', 'GK', 'Sub', 'RCM', 'CAM', 'LCB', 'LCM', 'RS',
       'RB', 'RCB', 'LM', 'LDM', 'RM', 'LB', 'CDM', 'RDM', 'LF', 'CB',
       'LAM', 'Res', 'CM', 'LS', 'RF', 'RWB', 'RAM', 'LWB', nan, 'CF'],
      dtype=object)

In [79]:
def posicion_jugador(pos):
    """Retorna posición en base a club_position."""
    if pos in ['ST', 'CF']:
        return "ataque"
    elif pos in ['RW', 'CAM', 'LW']:
        return "central_ataque" 
    elif pos in ['RM', 'CM', 'LM']:
        return "central"
    elif pos in ['RWB', 'CDM', 'LWB']:
        return "central_defensa"
    elif pos in ['RB', 'CB', 'LB']:
        return "defensa"
    elif pos in ['GK']:
        return "arquero"
    else:
        return np.nan

# Crear labels
y = df['Club_Position'].apply(posicion_jugador)

# Definir X (datos)
X = df.drop(columns=['Club_Position', 'National_Position']).copy()

# Filtrar valores Nan para no meter basura al modelo
no_es_nan = y.notna()
y = y[no_es_nan]
X = X[no_es_nan]

#### 2. Ejemplos por clase

In [80]:
y.value_counts()

Club_Position
defensa            1180
central             907
arquero             632
central_ataque      581
ataque              430
central_defensa     209
Name: count, dtype: int64

Nuevamente hay desbalance de clases, aunque no tan extremo como en el caso anterior, habiendo una mayor proporción de la posición "defensa" y menor de "central_defensa".

#### 3. Entremiento de nuevo Pipeline 

Justificación elección del modelo: hay menos de 100K muestras, por lo que se usará SGD Classifier.

In [83]:
# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Actualizamos column transformer con las columnas del X actual
numerical_features = X.select_dtypes('number').columns.tolist()
numerical_features = [x for x in numerical_features if x not in columns_to_drop]

categorical_features = X.select_dtypes('object').columns.tolist()
categorical_features = [x for x in categorical_features if x not in columns_to_drop]

col_transformer = ColumnTransformer([
    ('num', numerical_pipeline, numerical_features),
    ('cat', categorical_pipeline, categorical_features),
    ('drop_cols', ColumnDropper(columns_to_drop), columns_to_drop)
], 
remainder='passthrough',
verbose_feature_names_out=False)

# Nuevo pipeline para modelo SGD
pipeline_sgd = Pipeline([
    ('preprocessor', col_transformer),
    ('classifier',  SGDClassifier(
        random_state=42))
])

# Entrenar
pipeline_sgd.fit(X_train, y_train)

# Evaluar
y_pred_sgd = pipeline_sgd.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_sgd)
precision = precision_score(y_test, y_pred_sgd, average = 'macro')
recall = recall_score(y_test, y_pred_sgd, average = 'macro')

print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")  
print(f"Recall:    {recall:.4f}")

print(classification_report(y_test, y_pred_sgd))

Accuracy:  0.7069
Precision: 0.6412
Recall:    0.6210
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       126
         ataque       0.74      0.88      0.80        86
        central       0.50      0.71      0.59       182
 central_ataque       0.38      0.11      0.17       116
central_defensa       0.40      0.14      0.21        42
        defensa       0.83      0.87      0.85       236

       accuracy                           0.71       788
      macro avg       0.64      0.62      0.60       788
   weighted avg       0.68      0.71      0.67       788



#### 4. Comentarios

El desempeño de este modelo es bastante más satisfactorio. Si bien accuracy es más bajo que en el caso anterior, existe un mejor equilibrio entre las tres métricas globales. En cuanto a las métricas por clase, se sigue observando un mal desempeño en las clases minorotarias.

## 3. Predicciones de Seleccionados Nacionales para el Jere Klein [30 puntos]

<center>
<img src='https://www.radioactiva.cl/wp-content/uploads/2024/04/Jere-Klein-1-768x432.webp' width=500 />

Después de alcanzar la fama como cantante urbano, Jere Klein decide explorar una nueva faceta. Con su amor por el fútbol y convencido de que los artistas urbanos poseen un talento y versatilidad excepcionales, Jere se embarca en un proyecto innovador: desarrollar un sistema de inteligencia artificial capaz de identificar a jugadores que tienen potencial para convertirse en futbolistas profesionales. Su teoría es que muchos artistas del género urbano chileno, con sus habilidades únicas y su disciplina, podrían destacarse también en el deporte. Con este sistema, Jere espera no solo abrir nuevas oportunidades para sus colegas artistas, sino también demostrar la amplia gama de talentos que pueden ofrecer.

### 3.1 ¿Qué modelo de árbol es más de "pana"? [10 puntos]

<center>
<img src='https://64.media.tumblr.com/39189215a7d3d96823cb359f35b44e05/tumblr_psmrhrR3Xw1qf5hjqo4_540.gif' width=300 />


**Tareas**


1. Considerando el la variable llamada `label` creada en la sección 1.1. Para determinar cuál modelo de árbol sería más adecuado para la tarea en cuestión, utilice PyCaret. Este deberá centrarse exclusivamente en modelos de tipo árbol. Jere ha especificado que busca un modelo que tome decisiones rápidamente y que tenga una baja tasa de falsos positivos, ya que planea invertir en estos jugadores. [3 puntos]

Para la comparación, utilice los siguientes modelos:

```python
['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost']
```

2. Explique en brevemente que son los modelos de la siguiente lista `['et', 'rf', 'dt']` y como funcionan. [3 punto]

3. Tras realizar la comparación de modelos, seleccione aquel que muestre el mejor rendimiento en términos de velocidad y precisión, especialmente en la reducción de falsos positivos. Utilice la función `evaluate_model` de PyCaret para revisar y analizar los resultados obtenidos en los siguientes aspectos:

  - **Confusión Matrix**: ¿Cómo se encuentran la tasa de verdaderos positivos y verdaderos negativos?
  - **Threshold**: ¿Es acaso el umbral por defecto del modelo el mejor para las predicciones?
  - **Feature Importance**: ¿Cuáles son las variables con mejor desempeño? ¿A qué podría deberse esto?
  - **Learning Curve**: ¿El modelo presenta algún problema?

  [4 puntos]

**Respuesta**

In [ ]:
from pycaret.datasets import get_data
from pycaret.classification import *
import os

os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"

#Continuar código aquí

### 3.2 Reducción de dimensionalidad [14 puntos]

<center>
<img src='https://i.kym-cdn.com/photos/images/original/002/258/560/668.gif' width=400 />

A pesar de los resultados obtenidos previamente, el manager de Jere ha solicitado el entrenamiento de un modelo de XGBoost utilizando los datos disponibles. Además, se debe proceder a realizar una reducción de dimensionalidad basada en la importancia de las características.

Para llevar a cabo esta tarea:

1. Inicie entrenando un modelo XGBoost con todas las características disponibles. [2 puntos]

2. Una vez el modelo esté entrenado, evalúe y clasifique las características según su importancia de forma descendente. [2 puntos]

3. Utilice esta clasificación para ejecutar una búsqueda recursiva de eliminación de características, eliminando progresivamente las menos importantes y evaluando el impacto en el desempeño del modelo hasta identificar las N características más críticas. [2 puntos]

4. Con este conjunto reducido de características, entrene un nuevo modelo y evalúe su rendimiento. [2 puntos]

5. Posteriormente, responda a las siguientes preguntas para una comprensión más profunda de los cambios y beneficios:

  - ¿El rendimiento del modelo con las características seleccionadas es similar al del modelo original? ¿Cómo se comparan en términos de precisión y robustez? [2 puntos]
  - ¿Cuáles son los beneficios potenciales de eliminar variables del modelo? Considere factores como la simplificación del modelo, reducción del tiempo de entrenamiento, y mejora en la capacidad de generalización. [2 puntos]
  - Comente si el modelo con menor dimensionalidad es más sencillo de explicar. Explique brevemente por qué la eliminación de ciertas características puede facilitar la comprensión y la explicación del comportamiento del modelo. [2 puntos]

Notar que con esta metodologia buscamos encontrar un punto entermedio entre número de festures y desempeño. por esto, si observa que al aumentar festires el aumento es despreciable, puede no considerar agregar más features a su modelo.

**Respuesta**

### 3.3 Calibración Probabilistica [6 puntos]

<center>
<img src='https://media2.giphy.com/media/l2Je4Ku0Cx292KWv6/200w.gif?cid=6c09b952y0sihtq9tb6sz8j2023x3zxxp3qx1ocgonkpkblj&ep=v1_gifs_search&rid=200w.gif&ct=g' width=400 />

Para lograr modelos más modulares, se recomienda realizar una calibración del modelo entrenado anteriormente, con el objetivo de obtener salidas que reflejen mayor modularidad.

1. Se solicita que utilice un método de calibración que asegure que las probabilidades generadas incrementen de manera monótona. Una métrica ampliamente utilizada para evaluar la precisión de la calibración de un modelo es el Brier Score. Calcule el Brier Score para el modelo tanto antes como después de la calibración. Esto le permitirá realizar una comparación cuantitativa y determinar si la calibración ha mejorado el rendimiento del modelo. Para más información sobre el Brier Score, puede consultar el siguiente enlace: [Scikit-Learn - Brier Score Loss](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.brier_score_loss.html). [3 puntos]

2. Tras la calibración, examine y comente los resultados obtenidos. A su análisis añada una comparación visual de las ideales versus las salidas del modelo original (sin calibrar) y del modelo calibrado. [3 puntos]

**Respuesta**

Mucho éxito!

<center>
<img src="https://i.pinimg.com/originals/55/3d/42/553d42bea9b10e0662a05aa8726fc7f4.gif" width=300>